name: Update dependencies
concurrency: update-dependencies

on:
  schedule:
    # Every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
  issue_comment:
    types:
      - edited
  pull_request:
    types:
      - edited

jobs:
  update-dependencies:
    runs-on: [general-ubuntu]
    name: Update dependencies
    steps:
      - name: Update dependencies
        uses: open-turo/action-renovate@v1
        with:
          github-token: ${{ secrets.TURO_GITHUB_DEPENDENCY_MANAGER_TOKEN }}
          terraform-token: ${{ secrets.TERRAFORM_ENTERPRISE_ATLAS_TOKEN }}
